module Cards.Treasure exposing (Treasure(..))


type Treasure
    = BackbiterStaff
    | BellBookAndCandle
    | BlackWyrmEgg
    | BlessedSash
    | BlueWyrmEgg
    | BookOfKnowledge
    | CharmedPendant
    | CrystalShards
    | DoomOrb
    | DragonscaleShield
    | DurwoodBow
    | DwarvenShield
    | EldrichTome
    | ForsakenBlade
    | GathansGloves
    | GathansMail
    | GathansReach
    | GathansShield
    | GlovesOfAiming
    | GlovesOfMischief
    | GlovesOfStoring
    | GreenWyrmEgg
    | HelmOfFarsight
    | HealmOfLearning
    | InfernalSkull
    | KabalRing
    | KorsHammer
    | LifeBaneAmulet
    | LifeDrinker
    | MagicMirror
    | MassiveArmor
    | MedallionOfPain
    | PatchworkHelm
    | PileOfGold
    | PoisonKit
    | RejuvenatingPotion
    | PrelatesRod
    | RallyingHorn
    | RedWyrmEgg
    | RingOfFate
    | RingOfRemembrance
    | RodOfControl
    | ShardOfLogres
    | Skullblade
    | SwordOfAggression
    | TheQueensArmor
    | UlbracksHelm
    | UlbracksRing
    | UlbracksSteed
    | UlbracksSword
    | UnholyIdol
    | VengeanceTalons
    | WarDrum
    | WeaponPlans
    | WhiteWyrmEgg
